### ISSUE TITLE
calibration parser

### ISSUE THREAD

**Issue by rhaschke** [ubi-agni/tactile_toolbox#4]
* Why do you use the main key `calib`? Will there be any other key? My suggestion is to drop it and just use a sequence.
* The `sensor_name` is not used yet. Do we need it at all? Is that just for documentation?
* As far as I understand, `single_calib_` is used for all taxels if:
  * there is no multi-calib given at all
  * there is no `idx_range` given for any sequence item
  * there is a single, `negative` idx specified in `idx_range` for any sequence item
    I suggest to drop this last condition or replace it by `idx_range: default`. 
    My key suggestion is to use this as the default (or fallback) calib, if nothing more specific was defined for a taxel. Currently, `single_calib_` is only actually used when `calib_` is empty and calib_ is only used if it defines calibs for all taxel inputs.
    If we agree on this new semantics, I would cleanup the code some more towards this direction.

Hence, an example yaml config would look like this:
```yaml
tactile_calib:
  board0:
    - indices: [[44, 46], [50,56]]
      type: PWL
      values: { 0: 1 }
    - indices: [17, 18]
      type: PWL
      values: 
        0: 2
        1: 3
    - indices: default
      type: PWL
      values: 
        0: 2
        1: 3
    - indices: 42
      type: RAW
```
Handle, both C++ and python parser and dumper.
* C++:
  * parser: [tactile_state_calibrator](https://github.com/ubi-agni/tactile_toolbox/tree/melodic-devel/tactile_calibration/tactile_state_calibrator/src)
* python: 
  * parser/dumper: [mapping_utils.py](https://github.com/ubi-agni/tactile_toolbox/blob/melodic-devel/tactile_calibration/tactile_calibration_tools/src/tactile_calibration_tools/mapping_utils.py)
