### ISSUE TITLE
[rviz_tactile_plugin] contact_state display of "all taxels" is inconsistent

### ISSUE THREAD

**Issue by guihomework** [ubi-agni/tactile_toolbox#7]
I tried the tactile_merger new feature to use the no_clustering
`ROS_NAMESPACE=rh rosrun tactile_merger tactile_merger _no_clustering:=true`

and used the shadow hand + its UBI tip  (used gazebo as a producer for rsp+jsp + loading the urdf). was faster for me.
`roslaunch agni_deploy hand.launch`

produced some fake data with all tactile element at maximum value of 1.0
```
rostopic pub /rh/tactile_states tactile_msgs/TactileState -s -r 10 "header:
  seq: 0
  stamp: now
  frame_id: 'rh/rh_ffdistal'
sensors: 
  - 
    name: "rh_ffdistal"
    values: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]"
```

to finally display this in rviz.  I expect 1 arrow per taxel, so 12 arrows.
However it is not the case and I see a different set of arrows every time I deactivate/reactivate the plugin in rviz

![Screenshot_2020-10-05_13-10-27](https://user-images.githubusercontent.com/6583181/95073523-4cd61580-070d-11eb-81c3-334d38100ec4.png)
![Screenshot_2020-10-05_13-10-40](https://user-images.githubusercontent.com/6583181/95073531-4fd10600-070d-11eb-84e6-19c2e5146752.png)

I believe the contact_states are all there see the collapsed copy-paste, but maybe adding an id at the end of the name is confusing the display ?

<details><summary>contact states rostopic ouput</summary>
<p>

```
contacts: 
  - 
    header: 
      seq: 0
      stamp: 
        secs: 1558
        nsecs: 918000000
      frame_id: "rh_ffdistal"
    name: "rh_ffdistal_0"
    position: 
      x: 0.0042
      y: -0.0062
      z: 0.0146
    normal: 
      x: 0.373828955224
      y: -0.923334188309
      z: 0.0877831927893
    wrench: 
      force: 
        x: -0.373828955224
        y: 0.923334188309
        z: -0.0877831927893
      torque: 
        x: -0.012936423354
        y: -0.00508921333655
        z: 0.00156026406851
  - 
    header: 
      seq: 0
      stamp: 
        secs: 1558
        nsecs: 918000000
      frame_id: "rh_ffdistal"
    name: "rh_ffdistal_1"
    position: 
      x: 0.0086
      y: 0.0005
      z: 0.0132
    normal: 
      x: 0.998969699485
      y: -0.0326779574079
      z: 0.0314911195628
    wrench: 
      force: 
        x: -0.998969699485
        y: 0.0326779574079
        z: -0.0314911195628
      torque: 
        x: -0.000447094597566
        y: -0.012915576405
        z: 0.00078051528345
  - 
    header: 
      seq: 0
      stamp: 
        secs: 1558
        nsecs: 918000000
      frame_id: "rh_ffdistal"
    name: "rh_ffdistal_2"
    position: 
      x: 0.0083
      y: 0.0007
      z: 0.0195
    normal: 
      x: 0.995437947817
      y: -0.0371470644981
      z: 0.0878828063107
    wrench: 
      force: 
        x: -0.995437947817
        y: 0.0371470644981
        z: -0.0878828063107
      torque: 
        x: -0.000785885722131
        y: -0.0186816126901
        z: 0.00100512719881
  - 
    header: 
      seq: 0
      stamp: 
        secs: 1558
        nsecs: 918000000
      frame_id: "rh_ffdistal"
    name: "rh_ffdistal_3"
    position: 
      x: 0.0035
      y: -0.005
      z: 0.0239
    normal: 
      x: 0.366010911819
      y: -0.893475408353
      z: 0.260264686615
    wrench: 
      force: 
        x: -0.366010911819
        y: 0.893475408353
        z: -0.260264686615
      torque: 
        x: -0.0200527388266
        y: -0.00783673438932
        z: 0.00129710937014
  - 
    header: 
      seq: 0
      stamp: 
        secs: 1558
        nsecs: 918000000
      frame_id: "rh_ffdistal"
    name: "rh_ffdistal_4"
    position: 
      x: 0.0027
      y: 0.0006
      z: 0.0303
    normal: 
      x: 0.352136494502
      y: -0.13783813449
      z: 0.925743235417
    wrench: 
      force: 
        x: -0.352136494502
        y: 0.13783813449
        z: -0.925743235417
      torque: 
        x: -0.0047319414163
        y: -0.00817022904779
        z: 0.000583444859824
  - 
    header: 
      seq: 0
      stamp: 
        secs: 1558
        nsecs: 918000000
      frame_id: "rh_ffdistal"
    name: "rh_ffdistal_5"
    position: 
      x: 0.0071
      y: 0.001
      z: 0.0259
    normal: 
      x: 0.923019275018
      y: -0.0631404280814
      z: 0.379537487328
    wrench: 
      force: 
        x: -0.923019275018
        y: 0.0631404280814
        z: -0.379537487328
      torque: 
        x: -0.00201487457464
        y: -0.0212114830629
        z: 0.0013713163144
  - 
    header: 
      seq: 0
      stamp: 
        secs: 1558
        nsecs: 918000000
      frame_id: "rh_ffdistal"
    name: "rh_ffdistal_6"
    position: 
      x: -0.0071
      y: 0.001
      z: 0.0259
    normal: 
      x: -0.923019738848
      y: -0.0631336472015
      z: 0.379537487328
    wrench: 
      force: 
        x: 0.923019738848
        y: 0.0631336472015
        z: -0.379537487328
      torque: 
        x: -0.00201469894985
        y: 0.0212114950761
        z: -0.00137126863398
  - 
    header: 
      seq: 0
      stamp: 
        secs: 1558
        nsecs: 918000000
      frame_id: "rh_ffdistal"
    name: "rh_ffdistal_7"
    position: 
      x: -0.0027
      y: 0.0006
      z: 0.0303
    normal: 
      x: -0.352137507108
      y: -0.137835547547
      z: 0.925743235417
    wrench: 
      force: 
        x: 0.352137507108
        y: 0.137835547547
        z: -0.925743235417
      torque: 
        x: -0.00473186303193
        y: 0.00817025972975
        z: -0.000583438482642
  - 
    header: 
      seq: 0
      stamp: 
        secs: 1558
        nsecs: 918000000
      frame_id: "rh_ffdistal"
    name: "rh_ffdistal_8"
    position: 
      x: -0.0035
      y: -0.005
      z: 0.0239
    normal: 
      x: -0.366017475646
      y: -0.893472719462
      z: 0.260264686615
    wrench: 
      force: 
        x: 0.366017475646
        y: 0.893472719462
        z: -0.260264686615
      torque: 
        x: -0.0200526745621
        y: 0.00783689126478
        z: -0.00129706713989
  - 
    header: 
      seq: 0
      stamp: 
        secs: 1558
        nsecs: 918000000
      frame_id: "rh_ffdistal"
    name: "rh_ffdistal_9"
    position: 
      x: -0.0083
      y: 0.0007
      z: 0.0195
    normal: 
      x: -0.995438220688
      y: -0.0371397516016
      z: 0.0878828063107
    wrench: 
      force: 
        x: 0.995438220688
        y: 0.0371397516016
        z: -0.0878828063107
      torque: 
        x: -0.000785743120649
        y: 0.018681618011
        z: -0.00100506669277
  - 
    header: 
      seq: 0
      stamp: 
        secs: 1558
        nsecs: 918000000
      frame_id: "rh_ffdistal"
    name: "rh_ffdistal_10"
    position: 
      x: -0.0086
      y: 0.0005
      z: 0.0132
    normal: 
      x: -0.998969939523
      y: -0.0326706185658
      z: 0.0314911195628
    wrench: 
      force: 
        x: 0.998969939523
        y: 0.0326706185658
        z: -0.0314911195628
      torque: 
        x: -0.00044699772485
        y: 0.0129155795735
        z: -0.000780452289428
  - 
    header: 
      seq: 0
      stamp: 
        secs: 1558
        nsecs: 918000000
      frame_id: "rh_ffdistal"
    name: "rh_ffdistal_11"
    position: 
      x: -0.0042
      y: -0.0062
      z: 0.0146
    normal: 
      x: -0.373835738405
      y: -0.923331441983
      z: 0.0877831927893
    wrench: 
      force: 
        x: 0.373835738405
        y: 0.923331441983
        z: -0.0877831927893
      torque: 
        x: -0.0129363832577
        y: 0.005089312371
        z: -0.00156021047822

```

</p>
</details>
